#!/usr/bin/env python3
"""
run_ti_trained_controls_transfer.py

Fair control evaluation under the same protocol as the production backbone model:

    Ti-domain-only training
        -> no-retraining prediction on Al and Cu.

Two controls are evaluated.

1. temperature_only
   Quadratic temperature regression:
       dFres = a0 + a1*T + a2*T^2

2. response_only
   Temperature plus local von Mises stress statistics:
       [T, vMises_mean, vMises_std, vMises_q25,
        vMises_q50, vMises_q75, vMises_iqr]
   fitted with standardized RBF kernel ridge regression.

The target is always the gauge-fixed residual

    dFres = dFraw - C_s,

and the absolute free-energy prediction is reconstructed as

    F_pred = F0 + C_s + dFres_pred.

Protocol
--------
- Fitting uses only alpha-TiAl, beta-TiV, and Ti64 snapshots.
- Al/Cu targets are never used for fitting or hyperparameter selection.
- The Ti-domain internal result is generated by grouped out-of-fold prediction,
  using system-temperature groups.
- Al/Cu are predicted by one final model fitted to all Ti-domain snapshots.
- Prediction re-anchoring at T0 is applied using predictions only:
      dFres_pred*(T) =
          dFres_pred(T) - mean[dFres_pred(T0)]
  separately for each evaluated system.
  No external target is used for this step.

Inputs
------
table/piml_predictions_Ti.csv
table/piml_predictions_Al.csv
table/piml_predictions_Cu.csv

Outputs
-------
table/ti_trained_control_predictions.csv
table/ti_trained_control_summary_by_system_T.csv
table/ti_trained_control_summary_by_system.csv
table/ti_trained_control_summary_global.csv
table/ti_trained_control_ordering_within_system.csv
table/ti_trained_control_ordering_fixedT.csv
table/ti_trained_control_transfer_comparison.csv
table/ti_trained_control_audit.csv
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy.stats import kendalltau
from sklearn.base import clone
from sklearn.kernel_ridge import KernelRidge
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler


# ============================================================
# Paths and constants
# ============================================================
SCRIPT_DIR = Path(__file__).resolve().parent
TABLE_DIR = SCRIPT_DIR / "table"
TABLE_DIR.mkdir(parents=True, exist_ok=True)

TI_FILE = TABLE_DIR / "piml_predictions_Ti.csv"
AL_FILE = TABLE_DIR / "piml_predictions_Al.csv"
CU_FILE = TABLE_DIR / "piml_predictions_Cu.csv"

OUT_PRED = TABLE_DIR / "ti_trained_control_predictions.csv"
OUT_BY_ST = TABLE_DIR / "ti_trained_control_summary_by_system_T.csv"
OUT_BY_SYS = TABLE_DIR / "ti_trained_control_summary_by_system.csv"
OUT_GLOBAL = TABLE_DIR / "ti_trained_control_summary_global.csv"
OUT_WITHIN = TABLE_DIR / "ti_trained_control_ordering_within_system.csv"
OUT_FIXEDT = TABLE_DIR / "ti_trained_control_ordering_fixedT.csv"
OUT_TRANSFER = TABLE_DIR / "ti_trained_control_transfer_comparison.csv"
OUT_AUDIT = TABLE_DIR / "ti_trained_control_audit.csv"

TI_SYSTEMS = ("alpha-TiAl", "beta-TiV", "Ti64")
EXTERNAL_SYSTEMS = ("Al", "Cu")
T0 = 300.0
SEED = 0
MAX_GROUP_FOLDS = 5

REQUIRED_COLUMNS = {
    "system",
    "T",
    "FANC_eVatom",
    "F0_eVatom",
    "dFraw_T0_mean",
    "dFres_eVatom",
}

RESPONSE_FEATURE_CANDIDATES = (
    "vMises_mean",
    "vMises_std",
    "vMises_q25",
    "vMises_q50",
    "vMises_q75",
    "vMises_iqr",
)


# ============================================================
# Loading and validation
# ============================================================
def read_required_csv(path: Path, domain_label: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing input file: {path}\n"
            "Run run_piml_core_pipeline_backbone.py first."
        )

    frame = pd.read_csv(path)
    missing = sorted(REQUIRED_COLUMNS - set(frame.columns))
    if missing:
        raise ValueError(
            f"{path.name} is missing required columns: {missing}"
        )

    frame = frame.copy()
    frame["evaluation_domain"] = domain_label
    frame["__source_file"] = path.name

    numeric = [
        "T",
        "FANC_eVatom",
        "F0_eVatom",
        "dFraw_T0_mean",
        "dFres_eVatom",
    ]
    for column in numeric:
        frame[column] = pd.to_numeric(frame[column], errors="coerce")

    bad = frame[numeric].isna().any(axis=1)
    if bad.any():
        examples = frame.loc[
            bad,
            ["system", "T", "snap", "timestep"]
            if "snap" in frame.columns and "timestep" in frame.columns
            else ["system", "T"],
        ].head(10)
        raise ValueError(
            f"{path.name} contains invalid required numeric values.\n"
            + examples.to_string(index=False)
        )

    reconstructed = (
        frame["F0_eVatom"].to_numpy(float)
        + frame["dFraw_T0_mean"].to_numpy(float)
        + frame["dFres_eVatom"].to_numpy(float)
    )
    reference = frame["FANC_eVatom"].to_numpy(float)
    mismatch = float(np.max(np.abs(reconstructed - reference)))
    if mismatch > 5.0e-9:
        raise ValueError(
            f"{path.name} violates FANC = F0 + Cs + dFres. "
            f"Maximum mismatch={mismatch:.6e} eV/atom."
        )

    return frame.reset_index(drop=True)


def load_inputs() -> Tuple[pd.DataFrame, pd.DataFrame]:
    ti = read_required_csv(TI_FILE, "Ti_grouped_OOF")
    al = read_required_csv(AL_FILE, "external_no_retraining")
    cu = read_required_csv(CU_FILE, "external_no_retraining")

    ti_systems_present = set(ti["system"].astype(str).unique())
    missing_ti = [system for system in TI_SYSTEMS if system not in ti_systems_present]
    if missing_ti:
        raise ValueError(
            f"Ti input is missing expected systems: {missing_ti}"
        )

    external = pd.concat([al, cu], ignore_index=True, sort=False)

    key_columns = [
        column
        for column in ("system", "T", "snap", "timestep")
        if column in ti.columns and column in external.columns
    ]
    combined = pd.concat([ti, external], ignore_index=True, sort=False)
    if key_columns and combined.duplicated(key_columns).any():
        examples = combined.loc[
            combined.duplicated(key_columns, keep=False),
            key_columns,
        ].head(20)
        raise ValueError(
            "Duplicate snapshot keys detected across inputs:\n"
            + examples.to_string(index=False)
        )

    return ti, external


# ============================================================
# Metrics
# ============================================================
def safe_kendall(y_true: Sequence[float], y_pred: Sequence[float]) -> float:
    tau, _ = kendalltau(
        np.asarray(y_true, dtype=float),
        np.asarray(y_pred, dtype=float),
    )
    return np.nan if pd.isna(tau) else float(tau)


def pairwise_order_metrics(
    y_true: Sequence[float],
    y_pred: Sequence[float],
    tol: float = 1.0e-15,
) -> Tuple[float, float, int]:
    reference = np.asarray(y_true, dtype=float)
    prediction = np.asarray(y_pred, dtype=float)

    if len(reference) != len(prediction):
        raise ValueError("Reference and prediction lengths differ.")

    violations = 0
    total = 0

    for i in range(len(reference)):
        for j in range(i + 1, len(reference)):
            d_ref = reference[i] - reference[j]
            d_pred = prediction[i] - prediction[j]

            if abs(d_ref) <= tol:
                continue

            total += 1
            if abs(d_pred) <= tol or np.sign(d_ref) != np.sign(d_pred):
                violations += 1

    if total == 0:
        return np.nan, np.nan, 0

    return (
        float(violations / total),
        safe_kendall(reference, prediction),
        int(total),
    )


def regression_metrics(
    y_true: Sequence[float],
    y_pred: Sequence[float],
) -> Dict[str, float]:
    reference = np.asarray(y_true, dtype=float)
    prediction = np.asarray(y_pred, dtype=float)

    mae = float(mean_absolute_error(reference, prediction))
    rmse = float(np.sqrt(mean_squared_error(reference, prediction)))
    if len(reference) < 2 or np.isclose(np.var(reference), 0.0):
        r2 = np.nan
    else:
        r2 = float(r2_score(reference, prediction))

    return {"MAE": mae, "RMSE": rmse, "R2": r2}


# ============================================================
# Models
# ============================================================
def make_temperature_only_model() -> Pipeline:
    return Pipeline([
        ("poly", PolynomialFeatures(degree=2, include_bias=False)),
        ("linear", LinearRegression()),
    ])


def response_feature_columns(
    ti: pd.DataFrame,
    external: pd.DataFrame,
) -> List[str]:
    available = [
        column
        for column in RESPONSE_FEATURE_CANDIDATES
        if column in ti.columns and column in external.columns
    ]
    if not available:
        raise ValueError(
            "No common von Mises response features were found in Ti and "
            "external prediction files."
        )

    columns = ["T", *available]
    for frame_name, frame in (("Ti", ti), ("external", external)):
        for column in columns:
            frame[column] = pd.to_numeric(frame[column], errors="coerce")
        bad = frame[columns].isna().any(axis=1)
        if bad.any():
            raise ValueError(
                f"{frame_name} data contain missing response features: "
                f"{frame.loc[bad, ['system', 'T']].head(10).to_dict('records')}"
            )

    return columns


def make_response_only_model() -> Pipeline:
    return Pipeline([
        ("scaler", StandardScaler()),
        ("krr", KernelRidge(
            alpha=1.0e-2,
            kernel="rbf",
            gamma=0.2,
        )),
    ])


# ============================================================
# Fitting and prediction
# ============================================================
def grouped_oof_prediction(
    train_df: pd.DataFrame,
    feature_columns: Sequence[str],
    model: Pipeline,
) -> np.ndarray:
    x = train_df.loc[:, list(feature_columns)].to_numpy(dtype=float)
    y = train_df["dFres_eVatom"].to_numpy(dtype=float)

    groups = (
        train_df["system"].astype(str)
        + "_"
        + train_df["T"].astype(int).astype(str)
    ).to_numpy()

    n_splits = min(MAX_GROUP_FOLDS, len(np.unique(groups)))
    if n_splits < 2:
        raise ValueError("At least two system-temperature groups are required.")

    prediction = np.full(len(train_df), np.nan, dtype=float)
    splitter = GroupKFold(n_splits=n_splits)

    for fit_idx, test_idx in splitter.split(x, y, groups):
        fitted = clone(model)
        fitted.fit(x[fit_idx], y[fit_idx])
        prediction[test_idx] = fitted.predict(x[test_idx])

    if np.isnan(prediction).any():
        raise RuntimeError("Grouped OOF prediction left missing rows.")

    return prediction


def fit_full_ti_and_predict_external(
    ti: pd.DataFrame,
    external: pd.DataFrame,
    feature_columns: Sequence[str],
    model: Pipeline,
) -> Tuple[Pipeline, np.ndarray]:
    fitted = clone(model)
    fitted.fit(
        ti.loc[:, list(feature_columns)].to_numpy(dtype=float),
        ti["dFres_eVatom"].to_numpy(dtype=float),
    )

    prediction = fitted.predict(
        external.loc[:, list(feature_columns)].to_numpy(dtype=float)
    )
    return fitted, np.asarray(prediction, dtype=float)


def reanchor_prediction_by_system(
    df: pd.DataFrame,
    prediction: Sequence[float],
    t0: float = T0,
) -> np.ndarray:
    pred = np.asarray(prediction, dtype=float).copy()
    systems = df["system"].astype(str).to_numpy()
    temperatures = df["T"].to_numpy(dtype=float)

    for system in np.unique(systems):
        system_mask = systems == system
        anchor_mask = system_mask & np.isclose(temperatures, t0)

        if not anchor_mask.any():
            raise ValueError(
                f"System {system!r} has no T0={t0:g} rows for prediction re-anchoring."
            )

        pred[system_mask] -= float(np.mean(pred[anchor_mask]))

    return pred


def append_absolute_prediction(
    df: pd.DataFrame,
    method: str,
    residual_prediction: Sequence[float],
    protocol: str,
    feature_columns: Sequence[str],
) -> pd.DataFrame:
    out = df.copy()
    residual_prediction = np.asarray(residual_prediction, dtype=float)

    residual_column = f"dFpred_{method}"
    absolute_column = f"Fpred_{method}"

    out["method"] = method
    out["evaluation_protocol"] = protocol
    out["training_domain"] = "alpha-TiAl,beta-TiV,Ti64"
    out["external_targets_used_for_fit"] = False
    out["feature_columns"] = "|".join(feature_columns)
    out[residual_column] = residual_prediction
    out[absolute_column] = (
        out["F0_eVatom"].to_numpy(float)
        + out["dFraw_T0_mean"].to_numpy(float)
        + residual_prediction
    )
    out["signed_error_absF"] = (
        out[absolute_column].to_numpy(float)
        - out["FANC_eVatom"].to_numpy(float)
    )
    out["absolute_error_absF"] = np.abs(out["signed_error_absF"])
    out["signed_error_dFres"] = (
        residual_prediction
        - out["dFres_eVatom"].to_numpy(float)
    )
    out["absolute_error_dFres"] = np.abs(out["signed_error_dFres"])

    return out


# ============================================================
# Summaries
# ============================================================
def summarize_by_system_temperature(
    predictions: pd.DataFrame,
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for (
        protocol,
        method,
        system,
        temperature,
    ), subset in predictions.groupby(
        ["evaluation_protocol", "method", "system", "T"],
        observed=True,
        sort=True,
    ):
        absolute_col = f"Fpred_{method}"
        residual_col = f"dFpred_{method}"

        abs_metrics = regression_metrics(
            subset["FANC_eVatom"],
            subset[absolute_col],
        )
        residual_metrics = regression_metrics(
            subset["dFres_eVatom"],
            subset[residual_col],
        )

        rows.append({
            "evaluation_protocol": protocol,
            "method": method,
            "system": system,
            "T": int(temperature),
            "n_snapshots": len(subset),
            "MAE_absF": abs_metrics["MAE"],
            "RMSE_absF": abs_metrics["RMSE"],
            "R2_absF": abs_metrics["R2"],
            "MAE_dFres": residual_metrics["MAE"],
            "RMSE_dFres": residual_metrics["RMSE"],
            "R2_dFres": residual_metrics["R2"],
            "FANC_mean": subset["FANC_eVatom"].mean(),
            "Fpred_mean": subset[absolute_col].mean(),
            "state_bias_absF": (
                subset[absolute_col].mean()
                - subset["FANC_eVatom"].mean()
            ),
        })

    return pd.DataFrame(rows).sort_values(
        ["evaluation_protocol", "method", "system", "T"]
    ).reset_index(drop=True)


def summarize_by_system(
    predictions: pd.DataFrame,
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for (
        protocol,
        method,
        system,
    ), subset in predictions.groupby(
        ["evaluation_protocol", "method", "system"],
        observed=True,
        sort=True,
    ):
        absolute_col = f"Fpred_{method}"
        residual_col = f"dFpred_{method}"
        abs_metrics = regression_metrics(
            subset["FANC_eVatom"],
            subset[absolute_col],
        )
        residual_metrics = regression_metrics(
            subset["dFres_eVatom"],
            subset[residual_col],
        )
        fviol, tau, npairs = pairwise_order_metrics(
            subset["FANC_eVatom"],
            subset[absolute_col],
        )

        rows.append({
            "evaluation_protocol": protocol,
            "method": method,
            "system": system,
            "n_snapshots": len(subset),
            "MAE_absF": abs_metrics["MAE"],
            "RMSE_absF": abs_metrics["RMSE"],
            "R2_absF": abs_metrics["R2"],
            "MAE_dFres": residual_metrics["MAE"],
            "RMSE_dFres": residual_metrics["RMSE"],
            "R2_dFres": residual_metrics["R2"],
            "f_viol_snapshot_pairs": fviol,
            "tau_snapshot_pairs": tau,
            "n_snapshot_pairs": npairs,
        })

    return pd.DataFrame(rows).sort_values(
        ["evaluation_protocol", "method", "system"]
    ).reset_index(drop=True)


def summarize_global(
    predictions: pd.DataFrame,
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for (
        protocol,
        method,
    ), subset in predictions.groupby(
        ["evaluation_protocol", "method"],
        observed=True,
        sort=True,
    ):
        absolute_col = f"Fpred_{method}"
        residual_col = f"dFpred_{method}"

        abs_metrics = regression_metrics(
            subset["FANC_eVatom"],
            subset[absolute_col],
        )
        residual_metrics = regression_metrics(
            subset["dFres_eVatom"],
            subset[residual_col],
        )
        fviol, tau, npairs = pairwise_order_metrics(
            subset["FANC_eVatom"],
            subset[absolute_col],
        )

        rows.append({
            "evaluation_protocol": protocol,
            "method": method,
            "n_snapshots": len(subset),
            "MAE_absF": abs_metrics["MAE"],
            "RMSE_absF": abs_metrics["RMSE"],
            "R2_absF": abs_metrics["R2"],
            "MAE_dFres": residual_metrics["MAE"],
            "RMSE_dFres": residual_metrics["RMSE"],
            "R2_dFres": residual_metrics["R2"],
            "f_viol_snapshot_pairs": fviol,
            "tau_snapshot_pairs": tau,
            "n_snapshot_pairs": npairs,
        })

    return pd.DataFrame(rows).sort_values(
        ["evaluation_protocol", "method"]
    ).reset_index(drop=True)


def summarize_within_system_ordering(
    predictions: pd.DataFrame,
) -> pd.DataFrame:
    state_means = (
        predictions.groupby(
            ["evaluation_protocol", "method", "system", "T"],
            observed=True,
            as_index=False,
        )
        .agg(
            FANC_mean=("FANC_eVatom", "mean"),
            Fpred_mean=("signed_error_absF", lambda values: np.nan),
        )
    )

    # Avoid dynamic aggregation-column naming issues.
    state_rows: List[Dict[str, object]] = []
    for (
        protocol,
        method,
        system,
        temperature,
    ), subset in predictions.groupby(
        ["evaluation_protocol", "method", "system", "T"],
        observed=True,
        sort=True,
    ):
        absolute_col = f"Fpred_{method}"
        state_rows.append({
            "evaluation_protocol": protocol,
            "method": method,
            "system": system,
            "T": int(temperature),
            "FANC_mean": subset["FANC_eVatom"].mean(),
            "Fpred_mean": subset[absolute_col].mean(),
        })

    state_means = pd.DataFrame(state_rows)

    rows: List[Dict[str, object]] = []
    for (
        protocol,
        method,
        system,
    ), subset in state_means.groupby(
        ["evaluation_protocol", "method", "system"],
        observed=True,
        sort=True,
    ):
        subset = subset.sort_values("T")
        fviol, tau, npairs = pairwise_order_metrics(
            subset["FANC_mean"],
            subset["Fpred_mean"],
        )
        rows.append({
            "evaluation_protocol": protocol,
            "method": method,
            "system": system,
            "n_temperatures": len(subset),
            "f_viol": fviol,
            "tau": tau,
            "n_pairs": npairs,
        })

    return pd.DataFrame(rows).sort_values(
        ["evaluation_protocol", "method", "system"]
    ).reset_index(drop=True)


def summarize_fixed_temperature_ordering(
    predictions: pd.DataFrame,
) -> pd.DataFrame:
    state_rows: List[Dict[str, object]] = []

    for (
        protocol,
        method,
        system,
        temperature,
    ), subset in predictions.groupby(
        ["evaluation_protocol", "method", "system", "T"],
        observed=True,
        sort=True,
    ):
        absolute_col = f"Fpred_{method}"
        state_rows.append({
            "evaluation_protocol": protocol,
            "method": method,
            "system": system,
            "T": int(temperature),
            "FANC_mean": subset["FANC_eVatom"].mean(),
            "Fpred_mean": subset[absolute_col].mean(),
        })

    state_means = pd.DataFrame(state_rows)

    rows: List[Dict[str, object]] = []
    for (
        protocol,
        method,
        temperature,
    ), subset in state_means.groupby(
        ["evaluation_protocol", "method", "T"],
        observed=True,
        sort=True,
    ):
        subset = subset.sort_values("system")
        fviol, tau, npairs = pairwise_order_metrics(
            subset["FANC_mean"],
            subset["Fpred_mean"],
        )
        rows.append({
            "evaluation_protocol": protocol,
            "method": method,
            "T": int(temperature),
            "n_systems": len(subset),
            "f_viol": fviol,
            "tau": tau,
            "n_pairs": npairs,
        })

    return pd.DataFrame(rows).sort_values(
        ["evaluation_protocol", "method", "T"]
    ).reset_index(drop=True)


def build_transfer_comparison(
    by_system: pd.DataFrame,
    within_system: pd.DataFrame,
) -> pd.DataFrame:
    external_metrics = by_system[
        by_system["evaluation_protocol"].eq("external_no_retraining")
    ].copy()

    ordering = within_system[
        within_system["evaluation_protocol"].eq("external_no_retraining")
    ].copy()

    keep_ordering = ordering[
        ["method", "system", "f_viol", "tau", "n_pairs"]
    ].rename(columns={
        "f_viol": "within_system_f_viol",
        "tau": "within_system_tau",
        "n_pairs": "within_system_n_pairs",
    })

    result = external_metrics.merge(
        keep_ordering,
        on=["method", "system"],
        how="left",
        validate="one_to_one",
    )

    return result.sort_values(["system", "method"]).reset_index(drop=True)


# ============================================================
# Main
# ============================================================
def main() -> None:
    ti, external = load_inputs()

    response_columns = response_feature_columns(ti, external)

    method_specs = {
        "temp_only_ti_trained": {
            "features": ["T"],
            "model": make_temperature_only_model(),
        },
        "response_only_ti_trained": {
            "features": response_columns,
            "model": make_response_only_model(),
        },
    }

    prediction_frames: List[pd.DataFrame] = []

    for method, spec in method_specs.items():
        features = list(spec["features"])
        model = spec["model"]

        # Internal Ti-domain grouped OOF evaluation.
        ti_oof = grouped_oof_prediction(
            ti,
            features,
            model,
        )
        ti_oof = reanchor_prediction_by_system(ti, ti_oof, T0)
        prediction_frames.append(
            append_absolute_prediction(
                ti,
                method,
                ti_oof,
                "Ti_grouped_OOF",
                features,
            )
        )

        # Fit all Ti data once, then transfer without retraining to Al/Cu.
        _, external_prediction = fit_full_ti_and_predict_external(
            ti,
            external,
            features,
            model,
        )
        external_prediction = reanchor_prediction_by_system(
            external,
            external_prediction,
            T0,
        )
        prediction_frames.append(
            append_absolute_prediction(
                external,
                method,
                external_prediction,
                "external_no_retraining",
                features,
            )
        )

    predictions = pd.concat(
        prediction_frames,
        ignore_index=True,
        sort=False,
    )
    predictions.to_csv(OUT_PRED, index=False)

    by_system_temperature = summarize_by_system_temperature(predictions)
    by_system = summarize_by_system(predictions)
    global_summary = summarize_global(predictions)
    within_system = summarize_within_system_ordering(predictions)
    fixed_temperature = summarize_fixed_temperature_ordering(predictions)
    transfer_comparison = build_transfer_comparison(
        by_system,
        within_system,
    )

    by_system_temperature.to_csv(OUT_BY_ST, index=False)
    by_system.to_csv(OUT_BY_SYS, index=False)
    global_summary.to_csv(OUT_GLOBAL, index=False)
    within_system.to_csv(OUT_WITHIN, index=False)
    fixed_temperature.to_csv(OUT_FIXEDT, index=False)
    transfer_comparison.to_csv(OUT_TRANSFER, index=False)

    audit_rows = []
    for method, spec in method_specs.items():
        audit_rows.append({
            "method": method,
            "training_systems": ",".join(TI_SYSTEMS),
            "external_systems": ",".join(EXTERNAL_SYSTEMS),
            "target": "dFres_eVatom",
            "absolute_reconstruction": (
                "F0_eVatom+dFraw_T0_mean+dFres_prediction"
            ),
            "feature_columns": "|".join(spec["features"]),
            "external_targets_used_for_fit": False,
            "external_targets_used_for_tuning": False,
            "prediction_reanchoring_at_T0": True,
            "anchor_temperature_K": T0,
            "Ti_internal_protocol": "system_temperature_grouped_OOF",
            "external_protocol": "fit_all_Ti_then_predict_Al_Cu_without_retraining",
        })

    pd.DataFrame(audit_rows).to_csv(OUT_AUDIT, index=False)

    print("\n=== Ti-trained no-retraining transfer comparison ===")
    print(
        transfer_comparison[
            [
                "system",
                "method",
                "MAE_absF",
                "RMSE_absF",
                "within_system_f_viol",
                "within_system_tau",
            ]
        ].to_string(index=False)
    )

    print("\n=== Ti-domain grouped OOF controls ===")
    print(
        global_summary[
            global_summary["evaluation_protocol"].eq("Ti_grouped_OOF")
        ][
            [
                "method",
                "MAE_absF",
                "f_viol_snapshot_pairs",
                "tau_snapshot_pairs",
            ]
        ].to_string(index=False)
    )

    print("\nSaved:")
    for path in (
        OUT_PRED,
        OUT_BY_ST,
        OUT_BY_SYS,
        OUT_GLOBAL,
        OUT_WITHIN,
        OUT_FIXEDT,
        OUT_TRANSFER,
        OUT_AUDIT,
    ):
        print(" -", path)


if __name__ == "__main__":
    main()
